# Generated by Django 4.1.13 on 2024-04-03 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyset',
            name='folder',
        ),
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 10, 4, 46, 935305, tzinfo=datetime.timezone.utc)),
        ),
    ]
