# Generated by Django 4.1.13 on 2024-04-03 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_remove_studyset_folder_alter_folders_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyset',
            name='author',
        ),
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 3, 14, 41, 17, 66355, tzinfo=datetime.timezone.utc)),
        ),
    ]
