# Generated by Django 4.1.13 on 2024-04-11 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 1, 31, 14, 255107, tzinfo=datetime.timezone.utc)),
        ),
    ]
