# Generated by Django 4.1.13 on 2024-04-13 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 13, 10, 2, 263410, tzinfo=datetime.timezone.utc)),
        ),
    ]
