# Generated by Django 4.1.13 on 2024-04-14 07:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcard', '0006_alter_folders_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyset',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 7, 45, 1, 972395, tzinfo=datetime.timezone.utc)),
        ),
    ]
