# Generated by Django 4.1.13 on 2024-04-14 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_studyset_author_alter_folders_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyset',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 7, 48, 58, 87365, tzinfo=datetime.timezone.utc)),
        ),
    ]
