# Generated by Django 4.1.13 on 2024-04-22 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0009_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 22, 2, 59, 15, 489411, tzinfo=datetime.timezone.utc)),
        ),
    ]
