# Generated by Django 4.1.13 on 2024-05-01 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0012_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 0, 1, 16, 381515, tzinfo=datetime.timezone.utc)),
        ),
    ]
