# Generated by Django 4.1.13 on 2024-05-04 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0014_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 11, 2, 6, 863673, tzinfo=datetime.timezone.utc)),
        ),
    ]
