# Generated by Django 4.1.13 on 2024-05-17 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0016_alter_folders_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 2, 10, 27, 175624, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='ne_lan',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='vi', max_length=3),
        ),
        migrations.AlterField(
            model_name='word',
            name='or_lan',
            field=models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', max_length=3),
        ),
    ]
